        $(function(){
               $(document).on('click','.add-supplier',function(e){
                e.preventDefault();
                $("#modal-supplier").modal('show');
                $(".modal-title").html('TAMBAH SUPPLIER');
                $.get("view/supplier/supplier_form.php",
                    {id_pelamar:$(this).attr('data-id')},
                    function(html){
                        $(".modal-body").html(html);
                    }   
                );
            });
                $(document).on('click','.edit-record',function(e){
                e.preventDefault();
                $("#myModal").modal('show');
                $.get("view/fpk/hasil.php",
                {id_fpk:$(this).attr('data-id')},
                 function(html){
                        $(".modal-body").html(html);
                    }   
                );
            });
                $(document).on('click','.d-info',function(e){
                e.preventDefault();
                $("#detail-info").modal('show');
                $.get("view/info/info_detail.php",
                {id_info:$(this).attr('data-id')},
                 function(html){
                        $(".modal-body").html(html);
                    }   
                );
            });
                $(document).on('click','.ubah-seleksi',function(e){
                e.preventDefault();
                $("#modal-seleksi").modal('show');
                $.get("view/seleksi/ubah_seleksi.php",
                {id_info:$(this).attr('data-id')},
                 function(html){
                        $(".modal-body").html(html);
                    }   
                );
            });

                $(document).on('click','.m-nilai',function(e){
                e.preventDefault();
                $("#modal-nilai").modal('show');
                $.get("view/ujian/nilai_ujian.php",
                {id_app:$(this).attr('data-id')},
                 function(html){
                        $(".modal-body").html(html);
                    }   
                );
            });
        });