        $(function(){
               $(document).on('click','.add-supplier',function(e){
                e.preventDefault();
                $("#modal-supplier").modal('show');
                $(".modal-title").html('TAMBAH SUPPLIER');
                $.get("view/supplier/supplier_form.php",
                    {id_pelamar:$(this).attr('data-id')},
                    function(html){
                        $(".modal-body").html(html);
                    }   
                );
            });
                $(document).on('click','.ubah-supplier',function(e){
                e.preventDefault();
                $("#modal-ubah-supplier").modal('show');
                $(".modal-title").html('UBAH SUPPLIER');
                $.get("view/supplier/supplier_ubah.php",
                {id_supp:$(this).attr('data-id')},
                 function(html){
                        $(".modal-body").html(html);
                    }   
                );
            });
                $(document).on('click','.add-material',function(e){
                e.preventDefault();
                $("#modal-material").modal('show');
                 $(".modal-title").html('TAMBAH MATERIAL');
                $.get("view/material/material_form.php",
                {id_info:$(this).attr('data-id')},
                 function(html){
                        $(".modal-body").html(html);
                    }   
                );
            });
                $(document).on('click','.ubah-seleksi',function(e){
                e.preventDefault();
                $("#modal-seleksi").modal('show');
                $.get("view/seleksi/ubah_seleksi.php",
                {id_info:$(this).attr('data-id')},
                 function(html){
                        $(".modal-body").html(html);
                    }   
                );
            });

                $(document).on('click','.m-nilai',function(e){
                e.preventDefault();
                $("#modal-nilai").modal('show');
                $.get("view/ujian/nilai_ujian.php",
                {id_app:$(this).attr('data-id')},
                 function(html){
                        $(".modal-body").html(html);
                    }   
                );
            });
        });